# This is a basic workflow to help you get started with Actions

name: lolipop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --remote-root ${{ secrets.FTP_REMOTE_ROOT }}
          local-dir: portfolio
